name: Validation 
on:
  push:
    branches: 
    - main
    paths:
    - schema/**
  pull_request:
    branches: 
    - main
    paths:
    - schema/**

jobs:
  check-go:
    name: Run validate and test
    runs-on: yaml-validator-inc
    steps:
      - uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Display changed files
        run: |
          echo "Changed files: ${{ env.changed_files }}"
