name: Slack Notification on Pull Request Creation

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  notify_on_pr_create:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: 'custom'
          fields: repo,head_repo,author,head_sha,action,url,pull_request_number
          repo: ${{ github.repository }}
          head_repo: ${{ github.event.pull_request.head.repo.full_name }}
          author: ${{ github.event.pull_request.user.login }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          action: ${{ github.event_name }}
          url: ${{ github.event.pull_request.html_url }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

