name: Validation

on:
  push:
    branches: 
      - main
    paths:
      - schema/**
  pull_request:
    branches: 
      - main
    paths:
      - schema/**

jobs:
  Validate:
    name: Run Validate and Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Print GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Find Changed File in schema directory
        id: find-changed-file
        run: |
          git fetch --depth=1 origin main
          CHANGED_FILE=$(git diff --name-only origin/main HEAD schema/)
          if [ -z "$CHANGED_FILE" ]; then
            echo "No schema files were changed."
          else
            echo "Changed schema file: $CHANGED_FILE"
          fi
          # Set output using environment variable
          echo "::set-env name=CHANGED_FILE::${CHANGED_FILE}"

      - name: Send Slack message with Changed File (if applicable)
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Access the environment variable set in the previous step
          CHANGED_FILE: ${{ env.CHANGED_FILE }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "A new action has been completed.",
            "attachments": [
              {
                "color": "#36a64f",
                "title": "GitHub Actions Notification",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "'${{ github.repository }}'",
                    "short": true
                  },
                  {
                    "title": "Event",
                    "value": "'${{ github.event_name }}'",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "'${{ github.sha }}'",
                    "short": true
                  },
                  {
                    "title": "Changed Schema File",
                    "value": " ${{ steps.find-changed-file.outputs.changed_file || 'No schema files changed' }} ",
                    "short": true
                  }
                ]
              }
            ]
          }' $SLACK_WEBHOOK_URL

            ]
          }' $SLACK_WEBHOOK_URL
