name: Validation 
on:
  push:
    branches: 
    - main
    paths:
    - schema/**
  pull_request:
    branches: 
    - main
    paths:
    - schema/**

jobs:
  check-go:
    name: Run validate and test
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get changed files in a PR
        id: file_name
        run: |
          gh pr view $PR_NUMBER --json files --jq '.files.[].path' 2>&1
          all_changed_files=$(gh pr view "$PR_NUMBER" --json files --jq '.files.[].path')

