name: Validation

on:
  push:
    branches:
      - main
    paths:
      - 'schema/**'  # Use single quotes for clarity
  pull_request:
    branches:
      - main
    paths:
      - 'schema/**'  # Use single quotes for clarity

jobs:
  Validate:
    name: Run Validation and Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Use the latest checkout action version

      - name: Find Changed Files in schema directory
        id: find-changed-files
        run: |
          git fetch --depth=1 origin main  # Fetch the latest main branch
          CHANGED_FILES=$(git diff --name-only origin/main HEAD 'schema/**')  # Use a single quote for clarity and include the schema directory
          if [ -z "$CHANGED_FILES" ]; then
            echo "No schema files were changed."
          else
            echo "Changed schema files:"
            echo "$CHANGED_FILES"  # Print all changed files
          fi

          # Store changed files in a dedicated output variable for later use
          echo "::set-output name=CHANGED_FILES::$CHANGED_FILES"

      - name: Send Slack message with Changed File (if applicable)
        if: steps.find-changed-files.outputs.CHANGED_FILES  # Only run if files changed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Access secret Slack webhook URL
          CHANGED_FILE: ${{ steps.find-changed-files.outputs.CHANGED_FILES }}  # Access output variable from previous step
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            --data '{
              "text": "A new action has been completed.",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "GitHub Actions Notification",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "'${{ github.repository }}'",
                      "short": true
                    },
                    {
                      "title": "Event",
                      "value": "'${{ github.event_name }}'",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "'${{ github.sha }}'",
                      "short": true
                    },
                    {
                      "title": "Changed Schema File",
                      "value": " ${{ steps.find-changed-files.outputs.CHANGED_FILES || 'No schema files changed' }} ",
                      "short": true
                    }
                  ]
                }
              ]
            }' \
            $SLACK_WEBHOOK_URL
