name: Validation

on:
  push:
    branches: 
      - main
    paths:
      - schema/**
  pull_request:
    branches: 
      - main
    paths:
      - schema/**

jobs:
  Validate:
    name: Run Validate and Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Print GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Send Slack message
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "A new action has been completed.",
            "attachments": [
              {
                "color": "#36a64f",
                "title": "GitHub Actions Notification",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "'${{ github.repository }}'",
                    "short": true
                  },
                  {
                    "title": "Event",
                    "value": "'${{ github.event_name }}'",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "'${{ github.sha }}'",
                    "short": true
                  }
                ]
              }
            ]
          }' $SLACK_WEBHOOK_URL
